export {Welcome} from '@/screens/welcome';
export {Login} from '@/screens/login';
export {Signup} from '@/screens/signup';
export {HomeScreen} from '@/screens/home';
export {Pcities} from '@/screens/pcities';
export {MyJobs} from '@/screens/myjobs';
export {JobsDetails} from '@/screens/jobdetails';
export {Profile} from '@/screens/profile'
export {OnBoardingProfile,OnBoardingBankInfo} from '@/screens/onboarding'
export {Banks,City,State} from '@/screens/admin'